/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.20
 * Generated at: 2019-12-25 12:28:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\t<title>Insert title here</title>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write(" \t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  \t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\toverflow-x: hidden;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("\tcolor: white;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".heading{\r\n");
      out.write("\tbackground-color: rgb(204, 204, 204);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".nav2{\r\n");
      out.write("\tbackground-color: #0c6120;\r\n");
      out.write("\tfont-size: 13px;\r\n");
      out.write("    padding: 0px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".first{\r\n");
      out.write("\tbackground: url(img/abakus-grunder1.jpg);\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    height: 256px;\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write(".indigo{\r\n");
      out.write("\tbackground-color: #0c6120;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <div class=\"row first\" >\r\n");
      out.write("\t<div class=\"col col-md-12 col-sm-12 col-lg-12\">\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-sm\" style=\"background-color:#33363ae3;color: white\">\r\n");
      out.write("\t  <ul class=\"navbar-nav\">\r\n");
      out.write("\t    <li class=\"nav-item\">\r\n");
      out.write("\t      <a class=\"nav-link\" href=\"#\">Home</a>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item\">\r\n");
      out.write("\t      <a class=\"nav-link\" href=\"#\">Feedback</a>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item\">\r\n");
      out.write("\t      <a class=\"nav-link\" href=\"#\">Paymode</a>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item\">\r\n");
      out.write("\t      <a class=\"nav-link\" href=\"#\">Tracking</a>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item\">\r\n");
      out.write("\t      <a class=\"nav-link\" href=\"#\">Contact</a>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t  </ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write(" </div>\r\n");
      out.write("  <div class=\"row second\" >\r\n");
      out.write("\t<div class=\"col col-md-12 col-sm-12 col-lg-12\">\r\n");
      out.write("\t<nav class=\"navbar navbar-expand-sm nav2\" >\r\n");
      out.write("\t  <ul class=\"navbar-nav\" style=\"\">\r\n");
      out.write("\t     <li class=\"nav-item dropdown\">\r\n");
      out.write("\t      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">\r\n");
      out.write("\t        Student Abacus\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <div class=\"dropdown-menu\">\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">6 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">7 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">13 Rod Abacus</a>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item dropdown\">\r\n");
      out.write("\t      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">\r\n");
      out.write("\t        Course Materials\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <div class=\"dropdown-menu\">\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">5 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">6 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">7 Rod Abacus</a>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item dropdown\">\r\n");
      out.write("\t      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">\r\n");
      out.write("\t        Merchandise\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <div class=\"dropdown-menu\">\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">5 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">6 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">7 Rod Abacus</a>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item dropdown\">\r\n");
      out.write("\t      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">\r\n");
      out.write("\t        Special Course\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <div class=\"dropdown-menu\">\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">5 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">6 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">7 Rod Abacus</a>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item dropdown\">\r\n");
      out.write("\t      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">\r\n");
      out.write("\t        Links\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <div class=\"dropdown-menu\">\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">5 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">6 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">7 Rod Abacus</a>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t    <li class=\"nav-item dropdown\">\r\n");
      out.write("\t      <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbardrop\" data-toggle=\"dropdown\">\r\n");
      out.write("\t        Media Gallery\r\n");
      out.write("\t      </a>\r\n");
      out.write("\t      <div class=\"dropdown-menu\">\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">5 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">6 Rod Abacus</a>\r\n");
      out.write("\t        <a class=\"dropdown-item\" href=\"#\">7 Rod Abacus</a>\r\n");
      out.write("\t      </div>\r\n");
      out.write("\t    </li>\r\n");
      out.write("\t  </ul>\r\n");
      out.write("\t  <form class=\"form-inline\" action=\"/action_page.php\">\r\n");
      out.write("\t    <input class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\">\r\n");
      out.write("\t    <button class=\"btn btn-success\" type=\"submit\">Search</button>\r\n");
      out.write("\t  </form>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"container\" style=\"text-align:justify\">\r\n");
      out.write("\t<div class=\"row\" style=\"margin-top:10px\">\r\n");
      out.write("\t\t<div class=\"col col-md-9 col-xs-12 col-sm-12\">\r\n");
      out.write("\t\t\t<h5>Welcome to JAYAVARAD Graphics</h5>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col col-md-8\">\r\n");
      out.write("\t\t\t<p>We are one amongst the principal manufacturers, suppliers and exporters of optimum quality abacus.\r\n");
      out.write("\t\t\t</p><p>\r\n");
      out.write("\t\t\tWe are specialized in various types of student and teacher abacus and supply our products to many reputed abacus training institutions throughout India as well as across the Globe.\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t<p>We are a member of import-export code (IE Code) and to maintain our export status we follow essential measures in our production process.\r\n");
      out.write("\t\t\t</p><p>\r\n");
      out.write("\t\t\tWe provide prompt services, quick response and express sampling. We care for our customers and we understand Time is of immense importance to materialize orders. We look for customers for long-term partnership and we offer ourselves as very dependable, reliable, manufacturing partner who can make all possible efforts to serve our elite clientele.\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col col-md-4\">\r\n");
      out.write("\t\t\t\t<img src=\"img/abakus-grunder.jpg\" style=\"width:150px;\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"col col-md-12\">\r\n");
      out.write("\t\t\t\t<p>\r\n");
      out.write("\t\t\t\tWe have vast material resources and an efficient management to offer timely delivery of products. Our facilities assure quality inspection at various stages of procuring and manufacturing processes to ensure that the products meet the international norms. We offer premium quality products, reliable supply, on-schedule delivery and competitive prices.\r\n");
      out.write("\t\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\t\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"page-footer font-small indigo\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Footer Links -->\r\n");
      out.write("  <div class=\"container text-center text-md-left\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Grid row -->\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Grid column -->\r\n");
      out.write("      <div class=\"col-md-3 mx-auto\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Links -->\r\n");
      out.write("        <h5 class=\"font-weight-bold text-uppercase mt-3 mb-4\">MENU</h5>\r\n");
      out.write("\r\n");
      out.write("        <ul class=\"list-unstyled\">\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#!\">HOME</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#!\">PAYMODE</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#!\">TRACKING</a>\r\n");
      out.write("          </li>\r\n");
      out.write("          <li>\r\n");
      out.write("            <a href=\"#!\">USEFUL LINKS</a>\r\n");
      out.write("          </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("      <hr class=\"clearfix w-100 d-md-none\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Grid column -->\r\n");
      out.write("      <div class=\"col-md-6 mx-auto\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Links -->\r\n");
      out.write("        <h5 class=\"font-weight-bold text-uppercase mt-3 mb-4\">ENQUIRY</h5>\r\n");
      out.write("\r\n");
      out.write("        <form>\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t        \t<div class=\"col col-lg-12 col-sm-12 col-md-12\">\r\n");
      out.write("\t\t        \t<label>Name</label><br>\r\n");
      out.write("\t\t        \t<input type=\"text\" name=\"name\"/>\r\n");
      out.write("\t        \t</div>\r\n");
      out.write("        \t</div><br>\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t        \t<div class=\"col-md-12\">\r\n");
      out.write("\t\t        \t<label>Mobile No.</label><br>\r\n");
      out.write("\t\t        \t<input type=\"text\" name=\"mno\"/>\r\n");
      out.write("\t        \t</div>\r\n");
      out.write("        \t</div><br>\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t        \t<div class=\"col-md-12\">\r\n");
      out.write("\t\t        \t<label>Email</label><br>\r\n");
      out.write("\t\t        \t<input type=\"email\" name=\"email\"/>\r\n");
      out.write("\t        \t</div>\r\n");
      out.write("        \t</div><br>\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t        \t<div class=\"col-md-12\">\r\n");
      out.write("\t\t        \t<label>JV Indians Site FeedBack</label><br>\r\n");
      out.write("\t\t        \t<input type=\"text\" name=\"name\"/>\r\n");
      out.write("\t        \t</div>\r\n");
      out.write("        \t</div><br>\r\n");
      out.write("        \t<div class=\"row\">\r\n");
      out.write("\t        \t<div class=\"col-md-12\">\r\n");
      out.write("\t\t        \t<input type=\"submit\" name=\"submit\" value=\"submit\" style=\"background-color:black;color:white;padding:5px;\"/>\r\n");
      out.write("\t        \t</div>\r\n");
      out.write("        \t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("      <hr class=\"clearfix w-100 d-md-none\">\r\n");
      out.write("\r\n");
      out.write("      <!-- Grid column -->\r\n");
      out.write("      <div class=\"col-md-3 mx-auto\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Links -->\r\n");
      out.write("        <h5 class=\"font-weight-bold text-uppercase mt-3 mb-4\">CONTACT US</h5>\r\n");
      out.write("\t\t<p>Marketing Office</p>\r\n");
      out.write("\t\t<p>New No. 25, Old No.9, Chari Street,\r\n");
      out.write("\t\tNorth Usman Road,\r\n");
      out.write("\t\tT.Nagar, Chennai - 600017,\r\n");
      out.write("\t\tTamilnadu, India.\r\n");
      out.write("\t\tEmail : alagappan_sk@yahoo.com, info@jvindians.com\r\n");
      out.write("       </p>\r\n");
      out.write("       <p>Phone : 044-42071815<br>\r\n");
      out.write("\t\tTele Fax: 044-42071815\r\n");
      out.write("       </p>\r\n");
      out.write("       <p>Cell : (+91) - 098410 23115/7299923115</p>\t\r\n");
      out.write("      \t\r\n");
      out.write("      </div>\r\n");
      out.write("      <!-- Grid column -->\r\n");
      out.write("\r\n");
      out.write("      <hr class=\"clearfix w-100 d-md-none\">\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- Grid row -->\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Footer Links -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("  <div class=\"footer-copyright text-center py-3\">© 2018 Copyright:\r\n");
      out.write("    <a href=\"https://mdbootstrap.com/education/bootstrap/\"> MDBootstrap.com</a>\r\n");
      out.write("  </div>\r\n");
      out.write("  <!-- Copyright -->\r\n");
      out.write("\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
